### ISSUE TITLE
账号丢失了

### ISSUE THREAD

**Issue by stelvetica** [RSSNext/follow.is#4]
账号用的是github登录，显示名字为EssentialTreeTree，今天在安装follow本地时候，登录时候采用github登录，重新开始引导过程，下意识的把名字由stelvetica改为EssentialTreeTree，目前登录发现所有的订阅源和代币都没了。
现在手机上登录的账号还能正确使用。
补充：曾经错误的用过google账号登录。目前用google账号登录也是一样无订阅源和代币

**Comment by hyoban** [comment]
https://github.com/RSSNext/Follow/issues/2131
